DigitalUpskills/Models/tbl_Feedback.cs
namespace DigitalUpskills.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("[tbl.Feedback]")]
    public partial class tbl_Feedback
    {
        [Key]
        public int Feedback_Id { get; set; }

        [StringLength(50)]
        public string Feedback_Description { get; set; }

        [Column(TypeName = "date")]
        public DateTime Feedback_Date { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Feedback_Rating { get; set; }

        public int Student_Fid { get; set; }

        public int Course_Fid { get; set; }

        public virtual tbl_Student tbl_Student { get; set; }

        public virtual tbl_Course tbl_Course { get; set; }
    }
}

DigitalUpskills/Controllers/tbl_FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DigitalUpskills.Models;

namespace DigitalUpskills.Controllers
{
    public class tbl_FeedbackController : Controller
    {
        private Model1 db = new Model1();

        // GET: tbl_Feedback
        public ActionResult Index()
        {
            var tbl_Feedback = db.tbl_Feedback.Include(t => t.tbl_Student);
            return View(tbl_Feedback.ToList());
        }

        // GET: tbl_Feedback/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Feedback tbl_Feedback = db.tbl_Feedback.Find(id);
            if (tbl_Feedback == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Feedback);
        }

        // GET: tbl_Feedback/Create
        public ActionResult Create()
        {
            ViewBag.Student_Fid = new SelectList(db.tbl_Student, "Student_Id", "Student_Name");
            return View();
        }

        // POST: tbl_Feedback/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Feedback_Id,Feedback_Description,Feedback_Rating,Student_Fid")] tbl_Feedback tbl_Feedback)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Feedback.Add(tbl_Feedback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Student_Fid = new SelectList(db.tbl_Student, "Student_Id", "Student_Name", tbl_Feedback.Student_Fid);
            return View(tbl_Feedback);
        }

        // GET: tbl_Feedback/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Feedback tbl_Feedback = db.tbl_Feedback.Find(id);
            if (tbl_Feedback == null)
            {
                return HttpNotFound();
            }
            ViewBag.Student_Fid = new SelectList(db.tbl_Student, "Student_Id", "Student_Name", tbl_Feedback.Student_Fid);
            return View(tbl_Feedback);
        }

        // POST: tbl_Feedback/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Feedback_Id,Feedback_Description,Feedback_Rating,Student_Fid")] tbl_Feedback tbl_Feedback)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Student_Fid = new SelectList(db.tbl_Student, "Student_Id", "Student_Name", tbl_Feedback.Student_Fid);
            return View(tbl_Feedback);
        }

        // GET: tbl_Feedback/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Feedback tbl_Feedback = db.tbl_Feedback.Find(id);
            if (tbl_Feedback == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Feedback);
        }

        // POST: tbl_Feedback/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Feedback tbl_Feedback = db.tbl_Feedback.Find(id);
            db.tbl_Feedback.Remove(tbl_Feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DigitalUpskills/Views/tbl_Feedback/Create.cshtml
@model DigitalUpskills.Models.tbl_Feedback

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_Feedback</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Feedback_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Feedback_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Feedback_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Feedback_Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Feedback_Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Feedback_Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Student_Fid, "Student_Fid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Student_Fid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Student_Fid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DigitalUpskills/Views/tbl_Feedback/Delete.cshtml
@model DigitalUpskills.Models.tbl_Feedback

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_Feedback</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tbl_Student.Student_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Student.Student_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feedback_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feedback_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feedback_Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feedback_Rating)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DigitalUpskills/Views/tbl_Feedback/Details.cshtml
@model DigitalUpskills.Models.tbl_Feedback

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tbl_Feedback</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tbl_Student.Student_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_Student.Student_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feedback_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feedback_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feedback_Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feedback_Rating)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Feedback_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DigitalUpskills/Views/tbl_Feedback/Edit.cshtml
@model DigitalUpskills.Models.tbl_Feedback

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_Feedback</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Feedback_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Feedback_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Feedback_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Feedback_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Feedback_Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Feedback_Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Feedback_Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Student_Fid, "Student_Fid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Student_Fid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Student_Fid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DigitalUpskills/Views/tbl_Feedback/Index.cshtml
@model IEnumerable<DigitalUpskills.Models.tbl_Feedback>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>

    <a class="btn btn-primary glyphicon glyphicon-pencil" href="@Url.Action("Create","tbl_Feedback")"> Create New </a>
</p>
<table class="table">
    <tr>
        <th>
            Student Name
        </th>
        <th>
            Feedback Description
        </th>
        <th>
            Feedback Rating
        </th>
        <th></th>
    </tr>

    @foreach (var Feedback in Model)
    {
        <tr>
            <td>
                @Feedback.tbl_Student.Student_Name
            </td>
            <td>
                @Feedback.Feedback_Description
            </td>
            <td>
                @Feedback.Feedback_Rating
            </td>
            <td>
                <a class="btn btn-primary glyphicon glyphicon-edit" href="@Url.Action("Edit", "tbl_Feedback" , new{id= Feedback.Feedback_Id})"> Edit </a>
                <a class="btn btn-primary glyphicon glyphicon-book" href="@Url.Action("Details", "tbl_Feedback" , new{id= Feedback.Feedback_Id})"> Detail </a>
                <a class="btn btn-primary glyphicon glyphicon-trash" href="@Url.Action("Delete", "tbl_Feedback" , new{id= Feedback.Feedback_Id})"> Delete </a>
            </td>
        </tr>
    }

</table>