DigitalUpskills/Models/tbl_Instructor.cs
namespace DigitalUpskills.Models
{
    using DigitalUpskills.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("[tbl.Instructor]")]
    public partial class tbl_Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Instructor()
        {
            tbl_Course = new HashSet<tbl_Course>();
        }

        [Key]
        public int Instructor_Id { get; set; }

        public string Instructor_Image { get; set; }

        [Required]
        [StringLength(50)]
        public string Instructor_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Instructor_CNIC { get; set; }
        [Required]
        [StringLength(50)]
        public string Instructor_Qualification { get; set; }
        [Required]
        [StringLength(50)]
        public string Instructor_PhoneNo { get; set; }

        [Required]
        [StringLength(50)]
        public string Instructor_Gmail { get; set; }

        [Required]
        [StringLength(200)]
        public string Instructor_Address { get; set; }
        [Required]
        [StringLength(500)]
        public string Instructor_Detail { get; set; }
        [Required]
        [StringLength(50)]
        public string Instructor_Password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course> tbl_Course { get; set; }
    }
}

DigitalUpskills/Controllers/tbl_InstructorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DigitalUpskills.Models;

namespace DigitaalUpskills.Controllers
{
    public class tbl_InstructorController : Controller
    {
        private Model1 db = new Model1();

        // GET: tbl_Instructor
        public ActionResult Index()
        {
            return View(db.tbl_Instructor.ToList());
        }

        // GET: tbl_Instructor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Instructor tbl_Instructor = db.tbl_Instructor.Find(id);
            if (tbl_Instructor == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Instructor);
        }

        // GET: tbl_Instructor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tbl_Instructor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tbl_Instructor tbl_Instructor, HttpPostedFileBase pic)
        {
            string fullpath = Server.MapPath("~/Content/Projectpic/" + pic.FileName);
            pic.SaveAs(fullpath);
            tbl_Instructor.Instructor_Image = ("~/Content/Projectpic/" + pic.FileName);

            if (ModelState.IsValid)
            {
                db.tbl_Instructor.Add(tbl_Instructor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Instructor);
        }


        // GET: tbl_Instructor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Instructor tbl_Instructor = db.tbl_Instructor.Find(id);
            if (tbl_Instructor == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Instructor);
        }

        // POST: tbl_Instructor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Instructor tbl_Instructor = db.tbl_Instructor.Find(id);
            db.tbl_Instructor.Remove(tbl_Instructor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DigitalUpskills/Views/tbl_Instructor/Create.cshtml
@model DigitalUpskills.Models.tbl_Instructor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "tbl_Instructor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>tbl_Instructor</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_CNIC, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_CNIC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_CNIC, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_Detail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_Detail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_Detail, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_Qualification, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_Qualification, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_Qualification, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_PhoneNo, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="pic" required accept="img/*" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_Gmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_Gmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_Gmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Instructor_Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructor_Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instructor_Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DigitalUpskills/Views/tbl_Instructor/Delete.cshtml
@model DigitalUpskills.Models.tbl_Instructor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_CNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_CNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Qualification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Qualification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_PhoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Instructor_Image)" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Gmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Gmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DigitalUpskills/Views/tbl_Instructor/Details.cshtml
@model DigitalUpskills.Models.tbl_Instructor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tbl_Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_CNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_CNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Qualification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Qualification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_PhoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Instructor_Image)" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Gmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Gmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructor_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor_Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Instructor_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DigitalUpskills/Views/tbl_Instructor/Index.cshtml
<DigitalUpskills.Models.tbl_Instructor>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a class="btn btn-primary glyphicon glyphicon-pencil" href="@Url.Action("Create","tbl_Instructor")"> Create New </a>
</p>
<table class="table">
    <tr>
        <th>
            Instructor Name
        </th>
        <th>
            Instructor CNIC
        </th>
        <th>
            Instructor Detail
        </th>
        <th>
            Instructor Qualification
        </th>
        <th>
            Instructor PhoneNo
        </th>
        <th>
            Instructor Image
        </th>
        <th>
            Instructor Gmail
        </th>
        <th>
            Instructor Password
        </th>
        <th>
            Instructor Address
        </th>
        <th></th>
    </tr>

    @foreach (var Instructor in Model)
    {
        <tr>
            <td>
                @Instructor.Instructor_Name
            </td>

            <td>
                @Instructor.Instructor_CNIC
            </td>

            <td>
                @Instructor.Instructor_Detail
            </td>

            <td>
                @Instructor.Instructor_Qualification
            </td>

            <td>
                @Instructor.Instructor_PhoneNo
            </td>

            <td>
                <img src="@Url.Content(Instructor.Instructor_Image)" width="100" height="100" />
            </td>

            <td>
                @Instructor.Instructor_Gmail
            </td>

            <td>
                @Instructor.Instructor_Password
            </td>

            <td>
                @Instructor.Instructor_Address
            </td>

            <td>
        
                <a class="btn btn-primary glyphicon glyphicon-book" href="@Url.Action("Details", "tbl_Instructor" , new{id= Instructor.Instructor_Id})"> Detail </a>
                <a class="btn btn-primary glyphicon glyphicon-trash" href="@Url.Action("Delete", "tbl_Instructor" , new{id= Instructor.Instructor_Id})"> Delete </a>
            </td>
        </tr>
    }

</table>