DigitalUpskills/Controllers/BookmarkController.cs
using DigitalUpskills.Models;
using DigitalUpskills.Utills;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DigitalUpskills.Controllers
{
    public class BookmarkController : Controller
    {
        Model1 db = new Model1();
        // GET: Bookmark

        public ActionResult DisplayBookmark(int? id)
        {
            if (id != null)
            {
                var Bookmark = db.tbl_Bookmark.Where(x => x.Student_Fid == CurrentUser.CurrentStudent.Student_Id && x.Student_Fid == id).ToList();
                return View(Bookmark);
            }
            var bookmark = db.tbl_Bookmark.Where(x => x.Student_Fid == CurrentUser.CurrentStudent.Student_Id).ToList();
            return View(bookmark);
        }

        public ActionResult bookmark(int id)
        {
            if (CurrentUser.CurrentStudent == null)
            {
                return RedirectToAction("LoginStudent", "StudentLoginSystem");
            }

            if (db.tbl_Bookmark.Any(x => x.Course_Fid == id && x.Student_Fid == CurrentUser.CurrentStudent.Student_Id))
            {
                tbl_Bookmark bookmark = db.tbl_Bookmark.Where(x => x.Course_Fid == id && x.Student_Fid == CurrentUser.CurrentStudent.Student_Id).FirstOrDefault();
                db.tbl_Bookmark.Remove(bookmark);
                db.SaveChanges();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    tbl_Bookmark Bookmark = new tbl_Bookmark();
                    Bookmark.Course_Fid = id;
                    Bookmark.Student_Fid = CurrentUser.CurrentStudent.Student_Id;
                    db.tbl_Bookmark.Add(Bookmark);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Courses", "Home");
        }
    }
}

DigitalUpskills/Controllers/CartController.cs
using DigitalUpskills.Models;
using DigitalUpskills.Utills;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalUpskills.Controllers
{
    public class CartController : Controller
    {
        Model1 db = new Model1();
        //private object system;

        // GET: Cart
        public ActionResult Addtocart(int id)
        {
            List<tbl_Course> CartList = new List<tbl_Course>();
            if (Session["cart"] != null)
            {
                CartList = (List<tbl_Course>)Session["cart"];
            }
            tbl_Course tbl_Course = db.tbl_Course.Where(x => x.Course_Id == id).FirstOrDefault();
            CartList.Add(tbl_Course);
            Session["cart"] = CartList;

            return RedirectToAction("DisplayCart");

        }

        public ActionResult RemoveFromCart(int id)
        {
            List<tbl_Course> list = new List<tbl_Course>();
            list = (List<tbl_Course>)Session["cart"];
            list.RemoveAt(id);
            Session["cart"] = list;
            return View("DisplayCart");
        }

        public ActionResult PayNow()
        {
            return Redirect("https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_xclick&business=sb-dfpwc25010395@business.example.com&item_name=DigitalUpskillsCourses&return=http://localhost:44327/Cart/CourseRegistered&amount=" + double.Parse(Session["Total"].ToString())/277); 
        }

        public ActionResult DisplayCart()
        {
            return View();
        }
        public ActionResult Checkout()
        {
            if (CurrentUser.CurrentStudent == null)
            {
                return RedirectToAction("LoginStudent", "Home");
            }
            return View();
        }

        public ActionResult CourseRegistered(tbl_CourseRegistration registered)
        {
            List<tbl_Course> list = new List<tbl_Course>();
            list = (List<tbl_Course>)Session["cart"];
            var data = list.FirstOrDefault();
            registered.Status = "Registered";
            registered.Student_Fid = CurrentUser.CurrentStudent.Student_Id;
            registered.Registration_Date = DateTime.Now;
            registered.Course_Fid = data.Course_Id;
            db.tbl_CourseRegistration.Add(registered);
            db.SaveChanges();
            string mailBody = "Your Course Has Been Registered!";
            EmailProvider.Email(registered.Gmail, "Course Registered", mailBody);
            TempData["registered"] = Session["cart"];
            Session["cart"] = null;
            return RedirectToAction("RegistrationCompleted");
        }
        [HttpPost]
        public ActionResult ForgotPassword(string email)
        {
           var student= db.tbl_Student.Where( x=> x.Student_Gmail==email).FirstOrDefault();
            if (student == null)
            {
                TempData["error"] = "Invalid Email";
                return RedirectToAction("LoginStudent");
            }
           Random random = new Random();
            int code = random.Next(1001, 9999);
            Session["code"]=code;
            Session["userforgotpassword"]=student;
            Email.SendEmail(student.Student_Gmail,code);
            return RedirectToAction("codeverify");
            //string RecieverEmail = "";
            //string SubjEmail = "Subject";
            //Random R = new Random();
            //int a= R.Next(1000,9999);
            //string EmailBody = "Your Code Is" + a;
            //EmailProvider.Email(RecieverEmail, SubjEmail, EmailBody);
        }

        public ActionResult RegistrationCompleted()
        {
            return View();
        }

        public ActionResult codeverify()
        {
            return View();
        }
        [HttpPost]
        public ActionResult codeverify(int code)
        {
            int sendcode = (int)Session["code"];
            if (code == sendcode)
            {
                return RedirectToAction("NewPassword");
            }
            TempData["erro"] = "Invalid Code";
            return View();
        }
        public ActionResult NewPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewPassword(string password)
        {
            var user = (tbl_Student)Session["userforgotpassword"];
            var updatestudent= db.tbl_Student.Where(x => x.Student_Gmail == user.Student_Gmail).FirstOrDefault();
            updatestudent.Student_Password = password;
            db.Entry(updatestudent).State= EntityState.Modified;
            db.SaveChanges();
            TempData["msg"] = "Password Updated Successfully!";
            return RedirectToAction("LoginStudent");
        }
    }
}

DigitalUpskills/Controllers/CourseController.cs
using DigitalUpskills.Models;
using DigitalUpskills.Utills;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DigitalUpskills.Controllers
{
    public class CourseController : Controller
    {
        Model1 db = new Model1();
        // GET: Course
        public ActionResult CourseDetail(int id)
        {
            var courses = db.tbl_Course.Where(c => c.Course_Id == id).FirstOrDefault();
            return View(courses);
            //if (id == null)
            //{
            //   return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //tbl_Course Course = db.tbl_Course.Find(id);
            //if (Course == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(Course);
        }

        public ActionResult Feedback(tbl_Feedback feedback)
        {
            if (CurrentUser.CurrentStudent == null)
            {
                return RedirectToAction("LoginStudent", "StudentLoginSystem");
            }
            feedback.Feedback_Date = DateTime.Now;
            feedback.Student_Fid = CurrentUser.CurrentStudent.Student_Id;
            db.tbl_Feedback.Add(feedback);
            db.SaveChanges();
            return RedirectToAction("CourseDetail", "Course", new { id = feedback.Course_Fid });
        }
    }
}

DigitalUpskills/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using DigitalUpskills.Models;
using DigitalUpskills.Utills;

namespace DigitalUpskills.Controllers
{
    public class HomeController : Controller
    {
        Model1 db = new Model1();
        public ActionResult IndexUser()
        {
            string s = (string)TempData.Peek("Data");
            return View();
        }
       
        public ActionResult IndexAdmin()
        {
            return View();
        }
        public ActionResult CoursesByTeacher(int id)
        {
            var course=db.tbl_Course.Where(x => x.Instructor_Fid == id && x.Is_Approved==true).ToList();
            return View(course);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        } 
        public ActionResult CourseCategory()
            
        {
          
            return View();
        } 

        public ActionResult Courses(int? id,string Search)
        {
            SearchCourses data = new SearchCourses();

            if (Search != null)
            {
                var course = db.tbl_Course.Where(c => c.Is_Approved == true && c.Course_Name.StartsWith(Search)).ToList();
                data.Courses = course;
                return View(data);
            }
            else
            {
                var course = db.tbl_Course.Where(x => x.Is_Approved == true).ToList();
                data.Courses = course;
              
                if (id != null)
                {
                    ViewData["catid"] = id;
                    //ViewBag.catid = id;
                }
                ViewBag.Message = "Your application description page.";
                return View(data);
            }
        }

        public ActionResult Lectures(int? id)

        {
            if (id != null)
            {
                ViewData["lecid"] = id;
                //ViewBag.catid = id;
            }
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Slides(int? id)

        {
            if (id != null)
            {
                ViewData["sid"] = id;
                //ViewBag.catid = id;
            }

            ViewBag.Message = "Your application description page.";
            return View();
        }

   
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(tbl_Message Message)
        {

            if (ModelState.IsValid)
            {
                db.tbl_Message.Add(Message);
                db.SaveChanges();
                ViewBag.msg = "<script> alert('MESSAGE SENT!') </script>";

            }
            return View();
        }


        public ActionResult LoginInstructor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginInstructor(tbl_Instructor instructor)
        {
        //    TempData["Data"] = "Welcome to knowledge world!";
            if (instructor.Instructor_Name == null || instructor.Instructor_PhoneNo == null || instructor.Instructor_Address == null)
            {
                tbl_Instructor inst = db.tbl_Instructor.Where(x => x.Instructor_Gmail == instructor.Instructor_Gmail && x.Instructor_Password == instructor.Instructor_Password).FirstOrDefault();
                if (inst != null)
                {
                    CurrentUser.Currentinstructor = inst;
                    return RedirectToAction("InstructorDashboard","InstructorControls");
                }
                else
                {
                    ViewBag.msg = "<script> alert('Invalid Email & Password'</script>)";
                }
            }
             
            if (ModelState.IsValid)
            {
                db.tbl_Instructor.Add(instructor);
                db.SaveChanges();
                ViewBag.msg = "<script> alert('Account is created Successfully'</script>)";
            }
            return View("CreateCourse");
    }
        public ActionResult SignupInstructor()
        {
            return View();
        }
        public ActionResult ForgotInstructor()
        {
            return View();
        }
        public ActionResult Instructor(int? id)
        {
            if (id != null)
            {
                ViewData["catid"] = id;
            }
            return View();

        }

        public ActionResult InstructorLogout()
        {
            CurrentUser.Currentinstructor = null;
            return RedirectToAction("IndexUser", "Home");
        }

    }
}

DigitalUpskills/Views/Home/Courses.cshtml
@using DigitalUpskills.Models
@model DigitalUpskills.Utills.SearchCourses
@*@model List<DigitalUpskills.Models.tbl_Course>*@
@{ Layout = "~/views/shared/_LayoutUser.cshtml";
    Model1 db = new Model1();
}

<aside id="fh5co-hero">
    <div class="container">
        <div class="flexslider">
            <ul class="slides">
                <li style="background-image: url('../../Content/Projectpic/course (4).jpeg');">
                    <div class="overlay-gradient"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2 text-center slider-text">
                                <div class="slider-text-inner">
                                    <h1 class="heading-section">Our Course</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</aside>

<div id="fh5co-course">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
                <h2>Our Course</h2>
                <p>Here are available different courses to enhance student's skills and knowledge!</p>
            </div>
        </div>
        @using (Html.BeginForm("Courses", "Home", FormMethod.Get))
        {
            <div class="row">
                <div class="product-search">
                    <input type="text" name="Search" placeholder="Search">
                    <button type="submit"><i class="btn btn-search"></i>Search</button>
                </div>
            </div>
        }

        @foreach (var item in Model.Courses)
        {
            if (ViewData["catid"] == null || item.CourseCategory_Fid == (int)ViewData["catid"])
            {
                <div class="col-lg-4 col-md-4">
                    <div class="fh5co-blog animate-box">
                        <a href="#" class="course-img">
                            <img src="@Url.Content(item.Course_Image)" class="img-thumbnail" style="width:200% ;height: 200px">
                        </a>
                        <div class="blog-text">
                            <h3><a href="#">@item.Course_Name</a></h3>
                            <p>@item.Course_Detail</p>
                            <ul>
                                <li>
                                    <span data-toggle="modal" data-target="#course-modal">
                                        <a href="@Url.Action("CourseDetail","Course" , new {id = item.Course_Id})"><i class="icon-search3 btn btn-primary btn-sm btn-course"></i></a>
                                        <a href="@Url.Action("bookmark", "Bookmark", new { id = item.Course_Id})" class="icon-bookmark btn btn-primary btn-sm"></a>
                                        <a href="@Url.Action("AddToCart", "Cart", new { id = item.Course_Id })"><i class="icon-shopping-cart btn btn-primary btn-sm btn-course"></i></a> <br />
                                        @*<a href="@Url.Action("Lectures", "Home", new { id = item.Course_Id })">Lecture:<small class="text-muted"> (@item.tbl_Lecture.Count)</small></a> <br/>
                                        <a href="@Url.Action("Slides", "Home", new { id = item.Course_Id })">Slides:<small class="text-muted"> (@item.tbl_Lecture.Count)</small></a>*@

                                        @*<li>

                                            <a class=" icon-search3 btn btn-primary btn-sm btn-course" href="@Url.Action("CourseDetail","Home",new {id = item.Course_Id})"></a>
                                            <a class=" icon-bookmark btn btn-primary btn-sm btn-course" href="@Url.Action("Bookmark","Bookmark",new {id = item.Course_Id})"></a>
                                            <a href="@Url.Action("AddToCart", "Cart", new { id = item.Course_Id })"><i class="icon-shopping-cart btn btn-primary btn-sm btn-course"></i></a>

                                        </li>*@
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--<!-- Modal -->
                <!--<div class="modal course-modal fade" id="course-modal">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="tf-ion-close"></i>
                </button>
                <div class="modal-dialog " role="document">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-md-8 col-sm-6 col-xs-12">
                                    <div class="modal-image">
                                        <img class="img-responsive" src="@Url.Content(item.Course_Image)"--> @*alt="product-img"*@
                                        <!--/>
                                        </div>
                                        <div class="mask-icon">
                                            <ul>
                                                <li><a href="@Url.Action("CourseDetail", "Course", new { id = item.Course_Id })" data-toggle="tooltip" data-placement="right" title="View"><i class="btn icon-btn-play"></i></a></li>
                                                <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                            </ul>
                                            <a class="cart" href="#">Add to Cart</a>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        <div class="product-short-details">
                                            <h2 class="product-title">@item.Course_Name</h2>
                                            <p class="product-detail">Course Code: @item.Course_Code</p>
                                            <p class="product-detail">Course Duration: @item.Course_Duration</p>
                                            <p class="product-price">Course Fee: @item.Course_Fee</p>
                                            <p class="product-short-description">
                                                Course Detail: @item.Course_Detail
                                            </p>-->
                                        @*<a href="@Url.Action("DisplayBookmark", "Bookmark", new { id = item.Course_Id})" class="btn btn-primary">Bookmark</a>*@
                                        @*<a href="@Url.Action("AddToCart", "Cart", new { id = item.Course_Id })" class="btn btn-primary">Add To Cart</a>
                                                                    <a href="@Url.Action("CourseSingle","Home" , new { id = item.Course_Id })" class="btn btn-primary">View Course Details</a>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>-->*@
                                    }

                                    else if (item.CourseCategory_Fid == (int)(ViewData["catid"]))
                                    {
                                        <div class="col-md-6 animate-box">
                                            <div class="course">
                                                <a href="#" class="course-img">
                                                    <img src="@Url.Content(item.Course_Image)" style="width:100% ;height: 200px">

                                                </a>
                                                <div class="desc">
                                                    <h3><a href="#">@item.Course_Name</a></h3>
                                                    <h3><a href="#">@item.Course_Code</a></h3>
                                                    <p>@item.Course_Detail</p>
                                                    <span><a href="@Url.Action("Checkout","Cart", new { id=item.Course_Id})" class="btn btn-primary btn-sm btn-course">Take Course</a></span>

                                                </div>
                                            </div>
                                        </div>
                                    }
                                }

    </div>
</div>
@*</div>*@

DigitalUpskills/Views/Home/CoursesByTeacher.cshtml
@using DigitalUpskills.Models
@model List<DigitalUpskills.Models.tbl_Course>
@{ Layout = "~/views/shared/_LayoutUser.cshtml";
    Model1 db = new Model1();
}

<aside id="fh5co-hero">
    <div class="container">
        <div class="flexslider">
            <ul class="slides">
                <li style="background-image: url('../../Content/Projectpic/course (4).jpeg');">
                    <div class="overlay-gradient"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2 text-center slider-text">
                                <div class="slider-text-inner">
                                    <h1 class="heading-section">Our Course</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</aside>

<div id="fh5co-course">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
                <h2>Our Course</h2>
                <p>Here are available different courses to enhance student's skills and knowledge!</p>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                if (ViewData["catid"] == null || item.CourseCategory_Fid == (int)ViewData["catid"])
                {
                    <div class="col-lg-4 col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="course-img">
                                <img src="@Url.Content(item.Course_Image)" class="img-thumbnail" style="width:200% ;height: 200px">
                            </a>
                            <div class="blog-text">
                                <h3><a href="#">@item.Course_Name</a></h3>
                                <p>@item.Course_Detail</p>
                                  <ul>
                                    <li>
                                        <span data-toggle="modal" data-target="#course-modal">
                                            <a href="@Url.Action("CourseDetail","Course" , new {id = item.Course_Id})"><i class="icon-search3 btn btn-primary btn-sm btn-course"></i></a>
                                            <a href="@Url.Action("bookmark", "Bookmark", new { id = item.Course_Id})" class="icon-bookmark btn btn-primary btn-sm"></a>
                                            <a href="@Url.Action("AddToCart", "Cart", new { id = item.Course_Id })"><i class="icon-shopping-cart btn btn-primary btn-sm btn-course"></i></a> <br />
                                            @*<a href="@Url.Action("Lectures", "Home", new { id = item.Course_Id })">Lecture:<small class="text-muted"> (@item.tbl_Lecture.Count)</small></a> <br/>
                                                <a href="@Url.Action("Slides", "Home", new { id = item.Course_Id })">Slides:<small class="text-muted"> (@item.tbl_Lecture.Count)</small></a>*@
                                        </span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!--<!-- Modal -->
                    <!--<div class="modal course-modal fade" id="course-modal">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="tf-ion-close"></i>
                        </button>
                        <div class="modal-dialog " role="document">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-md-8 col-sm-6 col-xs-12">
                                            <div class="modal-image">
                                                <img class="img-responsive" src="@Url.Content(item.Course_Image)"--> @*alt="product-img"*@
                                                <!--/>
                                                    </div>
                                                    <div class="mask-icon">
                                                        <ul>
                                                            <li><a href="@Url.Action("CourseDetail", "Course", new { id = item.Course_Id })" data-toggle="tooltip" data-placement="right" title="View"><i class="btn icon-btn-play"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                                        </ul>
                                                        <a class="cart" href="#">Add to Cart</a>
                                                    </div>
                                                </div>
                                                <div class="col-md-4 col-sm-6 col-xs-12">
                                                    <div class="product-short-details">
                                                        <h2 class="product-title">@item.Course_Name</h2>
                                                        <p class="product-detail">Course Code: @item.Course_Code</p>
                                                        <p class="product-detail">Course Duration: @item.Course_Duration</p>
                                                        <p class="product-price">Course Fee: @item.Course_Fee</p>
                                                        <p class="product-short-description">
                                                            Course Detail: @item.Course_Detail
                                                        </p>-->
                                                @*<a href="@Url.Action("DisplayBookmark", "Bookmark", new { id = item.Course_Id})" class="btn btn-primary">Bookmark</a>*@
                                                @*<a href="@Url.Action("AddToCart", "Cart", new { id = item.Course_Id })" class="btn btn-primary">Add To Cart</a>
                                                                                <a href="@Url.Action("CourseSingle","Home" , new { id = item.Course_Id })" class="btn btn-primary">View Course Details</a>

                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>-->*@
                                            }

                                            else if (item.CourseCategory_Fid == (int)(ViewData["catid"]))
                                            {
                                                <div class="col-md-6 animate-box">
                                                    <div class="course">
                                                        <a href="#" class="course-img">
                                                            <img src="@Url.Content(item.Course_Image)" style="width:100% ;height: 200px">

                                                        </a>
                                                        <div class="desc">
                                                            <h3><a href="#">@item.Course_Name</a></h3>
                                                            <h3><a href="#">@item.Course_Code</a></h3>
                                                            <p>@item.Course_Detail</p>
                                                            <span><a href="@Url.Action("Checkout","Cart", new { id=item.Course_Id})" class="btn btn-primary btn-sm btn-course">Take Course</a></span>

                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        }

        </div>
    </div>
</div>