DigitalUpskills/Models/tbl_Course.cs
namespace DigitalUpskills.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("[tbl.Course]")]
    public partial class tbl_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Course()
        {
            tbl_CourseRegistration = new HashSet<tbl_CourseRegistration>();
            tbl_Lecture = new HashSet<tbl_Lecture>();
            tbl_Slide = new HashSet<tbl_Slide>();
            tbl_Feedback = new HashSet<tbl_Feedback>();
            tbl_Bookmark = new HashSet<tbl_Bookmark>();
        }

        [Key]
        public int Course_Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Course_Name { get; set; }

        [Required]
        public Boolean Is_Approved { get; set; }

        [Required]
        [StringLength(50)]
        public string Course_Code { get; set; }

        [StringLength(300)]
        public string Course_Detail { get; set; }

        public int Course_Fee { get; set; }

        [Required]
        [StringLength(50)]
        public string Course_Duration { get; set; }

       
        public string Course_Image { get; set; }

        public int Instructor_Fid { get; set; }
        public int CourseCategory_Fid { get; set; }

        public virtual tbl_CourseCategory tbl_CourseCategory { get; set; }

        public virtual tbl_Instructor tbl_Instructor { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CourseRegistration> tbl_CourseRegistration { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Lecture> tbl_Lecture { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Slide> tbl_Slide { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Feedback> tbl_Feedback { get; set; } 
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bookmark> tbl_Bookmark { get; set; }
    }
}

DigitalUpskills/Controllers/tbl_CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DigitalUpskills.Models;
using DigitalUpskills.Utills;

namespace DigitalUpskills.Controllers
{
    public class tbl_CourseController : Controller
    {
        private Model1 db = new Model1();

        // GET: tbl_Course
        public ActionResult Index()
        {
            var course = db.tbl_Course.Where(t => t.Instructor_Fid == CurrentUser.Currentinstructor.Instructor_Id).ToList();
            return View(course);
        }

        // GET: tbl_Course/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Course tbl_Course = db.tbl_Course.Find(id);
            if (tbl_Course == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Course);
        }

        // GET: tbl_Course/Create
        public ActionResult Create()
        {
            ViewBag.CourseCategory_Fid = new SelectList(db.tbl_CourseCategory, "CourseCategory_Id", "CourseCategory_Name");

            return View();
        }

        // POST: tbl_Course/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tbl_Course tbl_Course, HttpPostedFileBase pic)
        {
            string fullpath = Server.MapPath("~/Content/Projectpic/" + pic.FileName);
            pic.SaveAs(fullpath);
            tbl_Course.Course_Image = ("~/Content/Projectpic/" + pic.FileName);
            tbl_Course.Is_Approved = false;
            tbl_Course.Instructor_Fid = CurrentUser.Currentinstructor.Instructor_Id;
            db.tbl_Course.Add(tbl_Course);
            db.SaveChanges();
            ViewBag.CourseCategory_Fid = new SelectList(db.tbl_CourseCategory, "CourseCategory_Id", "CourseCategory_Name", tbl_Course.CourseCategory_Fid);
            return RedirectToAction("Index");
        }

        // GET: tbl_Course/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Course tbl_Course = db.tbl_Course.Find(id);
            if (tbl_Course == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseCategory_Fid = new SelectList(db.tbl_CourseCategory, "CourseCategory_Id", "CourseCategory_Name", tbl_Course.CourseCategory_Fid);
            ViewBag.Instructor_Fid = new SelectList(db.tbl_Instructor, "Instructor_Id", "Instructor_Name", tbl_Course.Instructor_Fid);
            return View(tbl_Course);
        }

        // POST: tbl_Course/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(tbl_Course tbl_Course, HttpPostedFileBase pic)
        {
            if (pic != null)
            {
                string fullpath = Server.MapPath("~/content/projectpic" + pic.FileName);
                pic.SaveAs(fullpath);
                tbl_Course.Course_Image = "~/content/projectpic" + pic.FileName;
            }

            if (ModelState.IsValid)
            {
                db.Entry(tbl_Course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseCategory_Fid = new SelectList(db.tbl_CourseCategory, "CourseCategory_Id", "CourseCategory_Name", tbl_Course.CourseCategory_Fid);
            ViewBag.Instructor_Fid = new SelectList(db.tbl_Instructor, "Instructor_Id", "Instructor_Name", tbl_Course.Instructor_Fid);
            return View(tbl_Course);
        }

        // GET: tbl_Course/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Course tbl_Course = db.tbl_Course.Find(id);
            if (tbl_Course == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Course);
        }

        // POST: tbl_Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Course tbl_Course = db.tbl_Course.Find(id);
            db.tbl_Course.Remove(tbl_Course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DigitalUpskills/Controllers/tbl_SlideController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DigitalUpskills.Models;
using DigitalUpskills.Utills;

namespace DigitalUpskills.Controllers
{
    public class tbl_SlideController : Controller
    {
        private Model1 db = new Model1();

        // GET: tbl_Slide
        public ActionResult Index()
        {
            var tbl_Slide = db.tbl_Slide.Include(t => t.tbl_Course);
            return View(tbl_Slide.ToList());
        }

        // GET: tbl_Slide/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Slide tbl_Slide = db.tbl_Slide.Find(id);
            if (tbl_Slide == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Slide);
        }

        // GET: tbl_Slide/Create
        public ActionResult Create()
        {
            ViewBag.Course_Fid = new SelectList(db.tbl_Course, "Course_Id", "Course_Name");
            return View();
        }

        // POST: tbl_Slide/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tbl_Slide tbl_Slide, HttpPostedFileBase pdf)
        {
            string fullpath = Server.MapPath("~/Content/Slides/" + pdf.FileName);
            pdf.SaveAs(fullpath);
            tbl_Slide.Slide_PDF = "~/Content/Slides/" +pdf.FileName;
            db.tbl_Slide.Add(tbl_Slide);
            db.SaveChanges();
            ViewBag.Course_Fid = new SelectList(db.tbl_Course, "Course_Id", "Course_Name", tbl_Slide.Course_Fid);
            return View(tbl_Slide);
        }

        // GET: tbl_Slide/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Slide tbl_Slide = db.tbl_Slide.Find(id);
            if (tbl_Slide == null)
            {
                return HttpNotFound();
            }
            ViewBag.Course_Fid = new SelectList(db.tbl_Course, "Course_Id", "Course_Name", tbl_Slide.Course_Fid);
            return View(tbl_Slide);
        }

        // POST: tbl_Slide/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(tbl_Slide tbl_Slide, HttpPostedFileBase pdf)
        {
            if (pdf != null)
            {
                string fullpath = Server.MapPath("~/content/Slides" + pdf.FileName);
                pdf.SaveAs(fullpath);
               // tbl_Slide.Slide_PDF = "~/content/Slides" + pdf.FileName;
            }

            if (ModelState.IsValid)
            {
                db.Entry(tbl_Slide).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Course_Fid = new SelectList(db.tbl_Course, "Course_Id", "Course_Name", tbl_Slide.Course_Fid);
            return View(tbl_Slide);
        }

        // GET: tbl_Slide/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Slide tbl_Slide = db.tbl_Slide.Find(id);
            if (tbl_Slide == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Slide);
        }

        // POST: tbl_Slide/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Slide tbl_Slide = db.tbl_Slide.Find(id);
            db.tbl_Slide.Remove(tbl_Slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DigitalUpskills/Views/tbl_Course/Create.cshtml
@model DigitalUpskills.Models.tbl_Course

@{
    Layout = "~/views/shared/_LayoutUser.cshtml";
    ViewBag.Title = "Create";
}
<aside id="fh5co-hero">
    <div class="flexslider">
        <ul class="slides">
            <li style="background-image: url('../../Content/Projectpic/course (4).jpeg');">
                <div class="overlay-gradient"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 text-center slider-text">
                            <div class="slider-text-inner">
                                <h1 class="heading-section">Start teaching and earning</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</aside>

<br />
<br />
<br />
<br />

@using (Html.BeginForm("Create", "tbl_Course", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Course_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pic" required accept="img/*" />
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.CourseCategory_Fid, "CourseCategory_Fid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseCategory_Fid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseCategory_Fid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DigitalUpskills/Views/tbl_Course/Delete.cshtml
@model DigitalUpskills.Models.tbl_Course

@{
    Layout = "~/views/shared/_LayoutUser.cshtml";
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tbl_CourseCategory.CourseCategory_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_CourseCategory.CourseCategory_Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Course_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Fee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Fee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Course_Image)" width="100" height="100" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DigitalUpskills/Views/tbl_Course/Details.cshtml
@model DigitalUpskills.Models.tbl_Course

@{
    Layout = "~/views/shared/_LayoutUser.cshtml";
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tbl_Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tbl_CourseCategory.CourseCategory_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_CourseCategory.CourseCategory_Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Course_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Fee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Fee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Image)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Course_Image)" width="100" height="100" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Course_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DigitalUpskills/Views/tbl_Course/Edit.cshtml
@model DigitalUpskills.Models.tbl_Course

@{
    Layout = "~/views/shared/_LayoutUser.cshtml";
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "tbl_Course", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>tbl_Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Course_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pic" />
                <img src="@Url.Content(Model.Course_Image)" width="100" height="100" />
                @Html.HiddenFor(model => model.Course_Image, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                @Html.ValidationMessageFor(model => model.Course_Image, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CourseCategory_Fid, "CourseCategory_Fid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseCategory_Fid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseCategory_Fid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DigitalUpskills/Views/tbl_Course/Index.cshtml
@model IEnumerable<DigitalUpskills.Models.tbl_Course>

@{
    Layout = "~/views/shared/_LayoutUser.cshtml";
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@foreach (var course in Model)
{
    <section class="user-dashboard page-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="dashboard-wrapper dashboard-user-profile">
                        <div class="media">
                            <div class="pull-left text-center" href="#!">
                                <img style="height:160px" class="media-object user-img" src="@Url.Content(course.Course_Image)" alt="Image">
                                <a href="#x" class="btn btn-transparent mt-20">Change Image</a>
                            </div>
                            <div class="media-body">
                                <ul class="user-profile-list">
                                    <li><span>Name:</span>@course.Course_Name</li>
                                    <li><span>Duration:</span>@course.Course_Duration</li>
                                    <li><span>Category:</span>@course.CourseCategory_Fid</li>
                                    <li><span>Fee:</span>@course.Course_Fee</li>
                                    <li><span>Detail:</span>@course.Course_Detail</li>

                                    <div class="col-md-6">
                                        <div>
                                            <div style="margin-right:50px ;padding-right:50px">
                                                <a class=" icon-pencil" href="@Url.Action("Edit", "tbl_Course" , new{id= course.Course_Id})"></a>
                                                <a class=" icon-book" href="@Url.Action("Details", "tbl_Course" , new{id= course.Course_Id})"> </a>
                                                <a class=" icon-trash" href="@Url.Action("Delete", "tbl_Course" , new{id= course.Course_Id})"></a>

                                            </div>
                                        </div>
                                        <div>
                                            <a class=" btn btn-outline" href="@Url.Action("Create", "tbl_Lecture", new{id= course.Course_Id})">Upload Lectures</a>
                                            <a class=" btn btn-outline" href="@Url.Action("Create", "tbl_Slide")">Upload Slides</a>
                                        </div>
                                    </div>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

@*<p>
        <a class="btn btn-primary glyphicon glyphicon-pencil" href="@Url.Action("Create","tbl_Course")"> Create New </a>
    </p>
    <table class="table">
        <tr>
            <th>
                CourseCategory Name
            </th>
            <th>
                Course Name
            </th>
            <th>
                Course Code
            </th>
            <th>
                Course Detail
            </th>
            <th>
                Course Fee
            </th>
            <th>
                Course Duration
            </th>
            <th>
                Course Image
            </th>
            <th></th>
        </tr>

        @foreach (var course in Model)
        {
            <tr>
                <td>
                    @course.tbl_CourseCategory.CourseCategory_Name
                </td>
                <td>
                    @course.Course_Name
                </td>
                <td>
                    @course.Course_Code
                </td>
                <td>
                    @course.Course_Detail
                </td>
                <td>
                    @course.Course_Fee
                </td>
                <td>
                    @course.Course_Duration
                </td>
                <td>
                    <img src="@Url.Content(course.Course_Image)" width="50" height="50" />
                </td>
                <td>
                    <div style="margin-right:50px ;padding-right:50px">
                        <a class=" icon-pencil" href="@Url.Action("Edit", "tbl_Course" , new{id= course.Course_Id})"></a>
                        <a class=" icon-book" href="@Url.Action("Details", "tbl_Course" , new{id= course.Course_Id})"> </a>
                        <a class=" icon-trash" href="@Url.Action("Delete", "tbl_Course" , new{id= course.Course_Id})"></a>

                    </div>
                </td>
                <td>
                    <div>
                        <a class=" btn btn-outline" href="@Url.Action("Create", "tbl_Lecture", new{id= course.Course_Id})">Upload Lectures</a>
                        <a class=" btn btn-outline" href="@Url.Action("Create", "tbl_Slide")">Upload Slides</a>
                    </div>
                </td>
            </tr>
        }


    </table>*@